# Generated by Django 6.0.7 on 2026-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
